name: Rspamd - rapid spam filtering system.
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/blog/page:num'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
description: Rspamd home.
url: http://rspamd.com
future: true
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
safe: true
