name: Rspamd - rapid spam filtering system.
highlighter: rouge
plugins:
  - jekyll-paginate

# Explicitly turn off the old code
paginate: 5
paginate_path: "/blog/page:num/"

description: Rspamd home.
url: http://rspamd.com
future: true
markdown: kramdown

kramdown:
  input: GFM
  Syntax_highlighter: rouge
