name: Rspamd - rapid spam filtering system.
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
paginate: 3
paginate_path: "blog/page:num"
description: Rspamd home.
url: http://rspamd.com
future: true
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
safe: true
