name: Rspamd - rapid spam filtering system.
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 3
paginate_path: "blog/page:num"
description: Rspamd home.
url: http://rspamd.com
future: true
markdown: redcarpet
redcarpet:
  extension: [
    "no_intra_emphasis",
    "tables",
    "autolink",
    "strikethrough",
    "with_toc_data",
    "fenced_code_blocks",
    "highlight",
    "superscript",
    "footnotes",
  ]

kramdown:
  input: GFM
  syntax_highlighter: rouge
