name: Rspamd - rapid spam filtering system.
gems: [jekyll-paginate]
highlighter: rouge
paginate: 3
paginate_path: "blog/page:num"
description: Rspamd home.
url: http://rspamd.com
keep_files: ["CentOS/6/os/x86_64/"]
future: true
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
