name: Rspamd - rapid spam filtering system.
markdown: kramdown
gems: [jekyll-paginate]
highlighter: pygments
paginate: 3
paginate_path: "blog/page:num"
description: Rspamd home.
url: http://rspamd.com
keep_files: ["CentOS/6/os/x86_64/"]
future: true
kramdown:
  input: GFM
